---
title: "Projet_bis"
author: "Yasmine Boulkaid, Cassandra Jan & Illana Rabasquinho"
date: "2024-04-09"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

#Librairies

```{r, echo=FALSE}
# Définir un miroir CRAN
options(repos = "https://cloud.r-project.org")

#install.packages("FactoMineR")
#install.packages("factoextra")
#install.packages("readxl")
#install.packages("gridExtra")

library(readxl)
library(gridExtra)
library(ggplot2)
library(FactoMineR)
library(factoextra)
library(conflicted)
library(dplyr)
library(tidyverse)
```

#Mise en forme des donnees 

```{r}
data <- read.csv("etude_sur_les_traitements_de_lendometriose_bis.csv")
n <- length(data)

head(data)
```

# On renomme les variables

```{r}

### Questions préliminaires ###
names(data)[names(data) == "Étude.sur.les.traitements.de.l.endométriose"] <- "ID"
names(data)[names(data) == "X"] <- "Age"
names(data)[names(data) == "X.1"] <- "Stade"
names(data)[names(data) == "X.2"] <- "Diagnostic"
names(data)[names(data) == "X.3"] <- "Tabac"
names(data)[names(data) == "X.4"] <- "Alcool"
names(data)[names(data) == "X.5"] <- "TH"
names(data)[names(data) == "X.6"] <- "CM"
names(data)[names(data) == "X.7"] <- "Autre"
names(data)[names(data) == "X.8"] <- "Aucun"
names(data)[names(data) == "X.9"] <- "Lesquels_M"


### Questions générales ###
Questions_Generales <- function(data,nb,TM){
  names(data)[names(data) == paste("X.", nb, sep="")] <- paste("Encore_", TM, sep="")
  names(data)[names(data) == paste("X.", nb+1, sep="")] <- paste("Depuis_", TM, sep="")
  names(data)[names(data) == paste("X.", nb+2, sep="")] <- paste("Debut_", TM, sep="")
  names(data)[names(data) == paste("X.", nb+3, sep="")] <- paste("Combien_", TM, sep="")
  names(data)[names(data) == paste("X.", nb+4, sep="")] <- paste("Pas_efficace_", TM, sep="")
  names(data)[names(data) == paste("X.", nb+5, sep="")] <- paste("ES_", TM, sep="")
  names(data)[names(data) == paste("X.", nb+6, sep="")] <- paste("Cout_", TM, sep="")
  names(data)[names(data) == paste("X.", nb+7, sep="")] <- paste("Autre_Cause_Fin_", TM, sep="")
  names(data)[names(data) == paste("X.", nb+8, sep="")] <- paste("Douleur_", TM, sep="")
  names(data)[names(data) == paste("X.", nb+9, sep="")] <- paste("Evolution_", TM, sep="")
  names(data)[names(data) == paste("X.", nb+10, sep="")] <- paste("Pre_op_", TM, sep="")
  names(data)[names(data) == paste("X.", nb+11, sep="")] <- paste("Post_op_", TM, sep="")
  names(data)[names(data) == paste("X.", nb+12, sep="")] <- paste("Pas_op_", TM, sep="")
  names(data)[names(data) == paste("X.", nb+13, sep="")] <- paste("Prise_", TM, sep="")
  return(data)
}
  

### Effets secondaires ###
Effets_Secondaires <- function(data,nb,TM,ES){
  names(data)[names(data) == paste("X.", nb+14, sep="")] <- paste("Subi_ES_", TM, sep="")
  names(data)[names(data) == paste("X.", nb+15, sep="")] <- paste("Tete_", TM, sep="")
  names(data)[names(data) == paste("X.", nb+16, sep="")] <- paste("Fatigue_", TM, sep="")
  names(data)[names(data) == paste("X.", nb+17, sep="")] <- paste("Nausee_", TM, sep="")
  names(data)[names(data) == paste("X.", nb+18, sep="")] <- paste("Humeur_", TM, sep="")
  names(data)[names(data) == paste("X.", nb+19, sep="")] <- paste("Libido_", TM, sep="")
  names(data)[names(data) == paste("X.", nb+20, sep="")] <- paste("Sang_", TM, sep="")
  names(data)[names(data) == paste("X.", nb+21, sep="")] <- paste("Poids_", TM, sep="")
  names(data)[names(data) == paste("X.", nb+22, sep="")] <- paste("Allergie_", TM, sep="")
  names(data)[names(data) == paste("X.", nb+23, sep="")] <- paste("Thrombose_", TM, sep="")
  names(data)[names(data) == paste("X.", nb+24, sep="")] <- paste("Autre_ES_", TM, sep="")
  
  a = 0
  f = 0
  
  for (i in seq_along(ES)){
    es <- ES[i]
    if (es != "Poids" && es != "Allergie"){
      names(data)[names(data) == paste("X.",nb+25+a*2, sep="")] <- paste("Apparition_",es,"_",TM, sep="")
      a <- a+1
    }
    if (es != "Thrombose" && es != "Poids" && es != "Allergie"){
      names(data)[names(data) == paste("X.",nb+26+f*2, sep="")] <- paste("Frequence_",es,"_",TM, sep="")
      f <- f+1
    }
  }
  return(data)
}


### Traitements non médicamenteux ###
Pris_En_Parallele <- function(data,nb,TM,TNM){
  names(data)[names(data) == paste("X.", nb+38, sep="")] <- paste("Mobilite_", TM, sep="")
  names(data)[names(data) == paste("X.", nb+39, sep="")] <- paste("Nutrition_", TM, sep="")
  names(data)[names(data) == paste("X.", nb+40, sep="")] <- paste("Stress_", TM, sep="")
  names(data)[names(data) == paste("X.", nb+41, sep="")] <- paste("Phyto_", TM, sep="")
  names(data)[names(data) == paste("X.", nb+42, sep="")] <- paste("Acup_", TM, sep="")
  names(data)[names(data) == paste("X.", nb+43, sep="")] <- paste("Hypnose_", TM, sep="")
  names(data)[names(data) == paste("X.", nb+44, sep="")] <- paste("Bouillotte_", TM, sep="")
  names(data)[names(data) == paste("X.", nb+45, sep="")] <- paste("CBD_", TM, sep="")
  names(data)[names(data) == paste("X.", nb+46, sep="")] <- paste("Tens_", TM, sep="")
  names(data)[names(data) == paste("X.", nb+47, sep="")] <- paste("Aucun_", TM, sep="")
  
    for (i in seq_along(TNM)){
    tnm <- TNM[i]
    names(data)[names(data) == paste("X.",nb+48+(i-1)*4, sep="")] <- paste("Combien_",tnm,"_", TM, sep="")
    names(data)[names(data) == paste("X.",nb+49+(i-1)*4, sep="")] <- paste("Douleur_",tnm,"_", TM, sep="")
    names(data)[names(data) == paste("X.",nb+50+(i-1)*4, sep="")] <- paste("Evolution_",tnm,"_", TM, sep="")
    names(data)[names(data) == paste("X.",nb+51+(i-1)*4, sep="")] <- paste("Prise_",tnm,"_", TM, sep="")
    }
  return(data)
}


## Traitement Hormonal ##
data <- Questions_Generales(data,10,"TH")

data <- Effets_Secondaires(data,10,"TH",c("Tete","Fatigue","Nausee","Humeur","Libido","Sang","Poids","Allergie","Thrombose"))

data <- Pris_En_Parallele(data,10,"TH",c("Mobilite","Nutrition","Stress","Phyto","Acup","Hypnose","Bouillotte","CBD","Tens"))


## Cure de Ménopause Artificielle ##
data <- Questions_Generales(data,94,"CM")

data <- Effets_Secondaires(data,94,"CM",c("Tete","Fatigue","Nausee","Humeur","Libido","Sang","Poids","Allergie","Thrombose"))

data <- Pris_En_Parallele(data,94,"CM",c("Mobilite","Nutrition","Stress","Phyto","Acup","Hypnose","Bouillotte","CBD","Tens"))


## Traitements Non Médicamenteux Seuls ##
names(data)[names(data) == "X.178"] <- "Mobilite_NM"
names(data)[names(data) == "X.179"] <- "Nutrition_NM"
names(data)[names(data) == "X.180"] <- "Stress_NM"
names(data)[names(data) == "X.181"] <- "Phyto_NM"
names(data)[names(data) == "X.182"] <- "Acup_NM"
names(data)[names(data) == "X.183"] <- "Hypnose_NM"
names(data)[names(data) == "X.184"] <- "Bouillotte_NM"
names(data)[names(data) == "X.185"] <- "CBD_NM"
names(data)[names(data) == "X.186"] <- "Tens_NM"
names(data)[names(data) == "X.187"] <- "Aucun_NM"

data <- Questions_Generales(data,188,"Mobilite_NM")
data <- Questions_Generales(data,202,"Nutrition_NM")
data <- Questions_Generales(data,216,"Stress_NM")
data <- Questions_Generales(data,230,"Phyto_NM")
data <- Questions_Generales(data,244,"Acup_NM")
data <- Questions_Generales(data,258,"Hypnose_NM")
data <- Questions_Generales(data,272,"Bouillotte_NM")
data <- Questions_Generales(data,286,"CBD_NM")
data <- Questions_Generales(data,300,"Tens_NM")


# Autres NM #
names(data)[names(data) == "X.314"] <- "Autres_NM"
names(data)[names(data) == "X.315"] <- "Lesquels_NM"


### Questions finales ###
names(data)[names(data) == "X.316"] <- "Remarques"
names(data)[names(data) == "X.317"] <- "Email"

head(data)

```


```{r}
### Supression des deux premières lignes ###
data <- data[-c(1:2), ]


### Questions préliminaires ###
data$Age = as.integer(data$Age)
data$Stade <- factor(data$Stade, levels = c("Stade I (superficielle)", "Stade II (modérée)", "Stade III (moyenne)", "Stade IV (profonde)"), ordered = TRUE)
data$Diagnostic = as.integer(data$Diagnostic)
data$Tabac <- factor(data$Tabac, levels = c("Régulièrement (consommation hebdomadaire)", "Parfois (en certaines occasions)", "Jamais"), ordered = TRUE)
data$Alcool <- factor(data$Alcool, levels = c("Régulièrement (consommation hebdomadaire)", "Parfois (en certaines occasions)", "Jamais"), ordered = TRUE)

TH <- ifelse(data$TH == "X", "y", "n")
data$TH <- factor(TH, levels = c("y", "n"), labels = c("yes", "no"))

CM <- ifelse(data$CM == "X", "y", "n")
data$CM <- factor(CM, levels = c("y", "n"), labels = c("yes", "no"))



### Questions générales TH ###

Depuis_TH <- ifelse(data$Depuis_TH == "", "0", data$Depuis_TH)
data$Depuis_TH <- factor(Depuis_TH, levels = c("Moins de 3 mois", "Entre 3 et 6 mois", "Entre 6 mois et 2 ans", "Entre 2 et 5 ans", "Plus de 5 ans"), ordered = TRUE)

Combien_TH <- ifelse(data$Combien_TH == "", "0", data$Combien_TH)
data$Combien_TH <- factor(Combien_TH, levels = c("Moins de 3 mois", "Entre 3 et 6 mois", "Entre 6 mois et 2 ans", "Entre 2 et 5 ans", "Plus de 5 ans"), ordered = TRUE)

Duree_TH <- factor(ifelse(is.na(data$Depuis_TH), as.character(data$Combien_TH), as.character(data$Depuis_TH)))

Douleur_TH <- ifelse(data$Douleur_TH == "", "0", data$Douleur_TH)
data$Douleur_TH <- factor(Douleur_TH, levels = c("Augmentation de la douleur", "Pas d'impact sur la douleur", "Réduction légère de la douleur", "Réduction importante de la douleur"), ordered = TRUE)

Evolution_TH <- ifelse(data$Evolution_TH == "", "0", data$Evolution_TH)
data$Evolution_TH <- factor(Evolution_TH, levels = c("Apparition de nouvelles lésions", "Grossissement des lésions déjà présentes", "Pas d'évolution", "Réduction modérée des lésions", "Réduction importante voire disparition des lésions", "Ne sais pas"), ordered = TRUE)

Tete_TH <- ifelse(data$Tete_TH == "X", "y", "n")
data$Tete_TH <- factor(Tete_TH, levels = c("y", "n"), labels = c("yes", "no"))

Fatigue_TH <- ifelse(data$Fatigue_TH == "X", "y", "n")
data$Fatigue_TH <- factor(Fatigue_TH, levels = c("y", "n"), labels = c("yes", "no"))

Nausee_TH <- ifelse(data$Nausee_TH == "X", "y", "n")
data$Nausee_TH <- factor(Nausee_TH, levels = c("y", "n"), labels = c("yes", "no"))

Humeur_TH <- ifelse(data$Humeur_TH == "X", "y", "n")
data$Humeur_TH <- factor(Humeur_TH, levels = c("y", "n"), labels = c("yes", "no"))

Libido_TH <- ifelse(data$Libido_TH == "X", "y", "n")
data$Libido_TH <- factor(Libido_TH, levels = c("y", "n"), labels = c("yes", "no"))

Sang_TH <- ifelse(data$Sang_TH == "X", "y", "n")
data$Sang_TH <- factor(Sang_TH, levels = c("y", "n"), labels = c("yes", "no"))

Poids_TH <- ifelse(data$Poids_TH == "X", "y", "n")
data$Poids_TH <- factor(Poids_TH, levels = c("y", "n"), labels = c("yes", "no"))

Allergie_TH <- ifelse(data$Allergie_TH == "X", "y", "n")
data$Allergie_TH <- factor(Allergie_TH, levels = c("y", "n"), labels = c("yes", "no"))

Thrombose_TH <- ifelse(data$Thrombose_TH == "X", "y", "n")
data$Thrombose_TH <- factor(Thrombose_TH, levels = c("y", "n"), labels = c("yes", "no"))

### Effets secondaires TH ###
Subi_ES_TH <- ifelse(data$Subi_ES_TH == "", "0", data$Subi_ES_TH)
data$Subi_ES_TH <- factor(Subi_ES_TH, levels = c("yes", "no"), ordered = TRUE)

Apparition_Tete_TH <- ifelse(data$Apparition_Tete_TH == "", "0", data$Apparition_Tete_TH)
data$Apparition_Tete_TH <- factor(Apparition_Tete_TH, levels = c("Moins de 3 mois", "Entre 3 et 6 mois", "Entre 6 mois et 2 ans", "Entre 2 et 5 ans", "Plus de 5 ans"), ordered = TRUE)

Frequence_Tete_TH <- ifelse(data$Frequence_Tete_TH == "", "0", data$Frequence_Tete_TH)
data$Frequence_Tete_TH <- factor(Frequence_Tete_TH, levels = c("Plusieurs fois par jour", "Plusieurs fois par semaine", "Plusieurs fois par mois", "Plusieurs fois par an", "Moins d'une fois par an"), ordered = TRUE)

Apparition_Fatigue_TH <- ifelse(data$Apparition_Fatigue_TH == "", "0", data$Apparition_Fatigue_TH)
data$Apparition_Fatigue_TH <- factor(Apparition_Fatigue_TH, levels = c("Moins de 3 mois", "Entre 3 et 6 mois", "Entre 6 mois et 2 ans", "Entre 2 et 5 ans", "Plus de 5 ans"), ordered = TRUE)

Frequence_Fatigue_TH <- ifelse(data$Frequence_Fatigue_TH == "", "0", data$Frequence_Fatigue_TH)
data$Frequence_Fatigue_TH <- factor(Frequence_Fatigue_TH, levels = c("Plusieurs fois par jour", "Plusieurs fois par semaine", "Plusieurs fois par mois", "Plusieurs fois par an", "Moins d'une fois par an"), ordered = TRUE)

Apparition_Nausee_TH <- ifelse(data$Apparition_Nausee_TH == "", "0", data$Apparition_Nausee_TH)
data$Apparition_Nausee_TH <- factor(Apparition_Nausee_TH, levels = c("Moins de 3 mois", "Entre 3 et 6 mois", "Entre 6 mois et 2 ans", "Entre 2 et 5 ans", "Plus de 5 ans"), ordered = TRUE)

Frequence_Nausee_TH <- ifelse(data$Frequence_Nausee_TH == "", "0", data$Frequence_Nausee_TH)
data$Frequence_Nausee_TH <- factor(Frequence_Nausee_TH, levels = c("Plusieurs fois par jour", "Plusieurs fois par semaine", "Plusieurs fois par mois", "Plusieurs fois par an", "Moins d'une fois par an"), ordered = TRUE)

Apparition_Humeur_TH <- ifelse(data$Apparition_Humeur_TH == "", "0", data$Apparition_Humeur_TH)
data$Apparition_Humeur_TH <- factor(Apparition_Humeur_TH, levels = c("Moins de 3 mois", "Entre 3 et 6 mois", "Entre 6 mois et 2 ans", "Entre 2 et 5 ans", "Plus de 5 ans"), ordered = TRUE)

Frequence_Humeur_TH <- ifelse(data$Frequence_Humeur_TH == "", "0", data$Frequence_Humeur_TH)
data$Frequence_Humeur_TH <- factor(Frequence_Humeur_TH, levels = c("Plusieurs fois par jour", "Plusieurs fois par semaine", "Plusieurs fois par mois", "Plusieurs fois par an", "Moins d'une fois par an"), ordered = TRUE)

Apparition_Libido_TH <- ifelse(data$Apparition_Libido_TH == "", "0", data$Apparition_Libido_TH)
data$Apparition_Libido_TH <- factor(Apparition_Libido_TH, levels = c("Moins de 3 mois", "Entre 3 et 6 mois", "Entre 6 mois et 2 ans", "Entre 2 et 5 ans", "Plus de 5 ans"), ordered = TRUE)

Frequence_Libido_TH <- ifelse(data$Frequence_Libido_TH == "", "0", data$Frequence_Libido_TH)
data$Frequence_Libido_TH <- factor(Frequence_Libido_TH, levels = c("Plusieurs fois par jour", "Plusieurs fois par semaine", "Plusieurs fois par mois", "Plusieurs fois par an", "Moins d'une fois par an"), ordered = TRUE)

Apparition_Sang_TH <- ifelse(data$Apparition_Sang_TH == "", "0", data$Apparition_Sang_TH)
data$Apparition_Sang_TH <- factor(Apparition_Sang_TH, levels = c("Moins de 3 mois", "Entre 3 et 6 mois", "Entre 6 mois et 2 ans", "Entre 2 et 5 ans", "Plus de 5 ans"), ordered = TRUE)

Frequence_Sang_TH <- ifelse(data$Frequence_Sang_TH == "", "0", data$Frequence_Sang_TH)
data$Frequence_Sang_TH <- factor(Frequence_Sang_TH, levels = c("Plusieurs fois par jour", "Plusieurs fois par semaine", "Plusieurs fois par mois", "Plusieurs fois par an", "Moins d'une fois par an"), ordered = TRUE)

Apparition_Thrombose_TH <- ifelse(data$Apparition_Thrombose_TH == "", "0", data$Apparition_Thrombose_TH)
data$Apparition_Thrombose_TH <- factor(Apparition_Thrombose_TH, levels = c("Moins de 3 mois", "Entre 3 et 6 mois", "Entre 6 mois et 2 ans", "Entre 2 et 5 ans", "Plus de 5 ans"), ordered = TRUE)

### Traitements non médicamenteux TH ###
Mobilite_TH <- ifelse(data$Mobilite_TH == "X", "y", "n")
data$Mobilite_TH <- factor(Mobilite_TH, levels = c("y", "n"), labels = c("yes", "no"))

Nutrition_TH <- ifelse(data$Nutrition_TH == "X", "y", "n")
data$Nutrition_TH <- factor(Nutrition_TH, levels = c("y", "n"), labels = c("yes", "no"))

Stress_TH <- ifelse(data$Stress_TH == "X", "y", "n")
data$Stress_TH <- factor(Stress_TH, levels = c("y", "n"), labels = c("yes", "no"))

Phyto_TH <- ifelse(data$Phyto_TH == "X", "y", "n")
data$Phyto_TH <- factor(Phyto_TH, levels = c("y", "n"), labels = c("yes", "no"))

Acup_TH <- ifelse(data$Acup_TH == "X", "y", "n")
data$Acup_TH <- factor(Acup_TH, levels = c("y", "n"), labels = c("yes", "no"))

Hypnose_TH <- ifelse(data$Hypnose_TH == "X", "y", "n")
data$Hypnose_TH <- factor(Hypnose_TH, levels = c("y", "n"), labels = c("yes", "no"))

Bouillotte_TH <- ifelse(data$Bouillotte_TH == "X", "y", "n")
data$Bouillotte_TH <- factor(Bouillotte_TH, levels = c("y", "n"), labels = c("yes", "no"))

CBD_TH <- ifelse(data$CBD_TH == "X", "y", "n")
data$CBD_TH <- factor(CBD_TH, levels = c("y", "n"), labels = c("yes", "no"))

Tens_TH <- ifelse(data$Tens_TH == "X", "y", "n")
data$Tens_TH <- factor(Tens_TH, levels = c("y", "n"), labels = c("yes", "no"))

Aucun_TH <- ifelse(data$Aucun_TH == "X", "y", "n")
data$Aucun_TH <- factor(Aucun_TH, levels = c("y", "n"), labels = c("yes", "no"))

# Mobilité TH #
Combien_Mobilite_TH <- ifelse(data$Combien_Mobilite_TH == "", "0", data$Combien_Mobilite_TH)
data$Combien_Mobilite_TH <- factor(Combien_Mobilite_TH, levels = c("Moins de 3 mois", "Entre 3 et 6 mois", "Entre 6 mois et 2 ans", "Entre 2 et 5 ans", "Plus de 5 ans"), ordered = TRUE)

Douleur_Mobilite_TH <- ifelse(data$Douleur_Mobilite_TH == "", "0", data$Douleur_Mobilite_TH)
data$Douleur_Mobilite_TH <- factor(Douleur_Mobilite_TH, levels = c("Augmentation de la douleur", "Pas d'impact sur la douleur", "Diminution de la douleur"), ordered = TRUE)

Evolution_Mobilite_TH <- ifelse(data$Evolution_Mobilite_TH == "", "0", data$Evolution_Mobilite_TH)
data$Evolution_Mobilite_TH <- factor(Evolution_Mobilite_TH, levels = c("Augmentation des lésions", "Pas d'impact sur les lésions", "Réduction des lésions", "Ne sais pas"), ordered = TRUE)


# Nutrition TH #
Combien_Nutrition_TH <- ifelse(data$Combien_Nutrition_TH == "", "0", data$Combien_Nutrition_TH)
data$Combien_Nutrition_TH <- factor(Combien_Nutrition_TH, levels = c("Moins de 3 mois", "Entre 3 et 6 mois", "Entre 6 mois et 2 ans", "Entre 2 et 5 ans", "Plus de 5 ans"), ordered = TRUE)

Douleur_Nutrition_TH <- ifelse(data$Douleur_Nutrition_TH == "", "0", data$Douleur_Nutrition_TH)
data$Douleur_Nutrition_TH <- factor(Douleur_Nutrition_TH, levels = c("Augmentation de la douleur", "Pas d'impact sur la douleur", "Diminution de la douleur"), ordered = TRUE)

Evolution_Nutrition_TH <- ifelse(data$Evolution_Nutrition_TH == "", "0", data$Evolution_Nutrition_TH)
data$Evolution_Nutrition_TH <- factor(Evolution_Nutrition_TH, levels = c("Apparition de nouvelles lésions", "Grossissement des lésions déjà présentes", "Pas d'évolution", "Réduction modérée des lésions", "Réduction importante voire disparition des lésions", "Ne sais pas"), ordered = TRUE)


# Stress TH #
Combien_Stress_TH <- ifelse(data$Combien_Stress_TH == "", "0", data$Combien_Stress_TH)
data$Combien_Stress_TH <- factor(Combien_Stress_TH, levels = c("Moins de 3 mois", "Entre 3 et 6 mois", "Entre 6 mois et 2 ans", "Entre 2 et 5 ans", "Plus de 5 ans"), ordered = TRUE)

Douleur_Stress_TH <- ifelse(data$Douleur_Stress_TH == "", "0", data$Douleur_Stress_TH)
data$Douleur_Stress_TH <- factor(Douleur_Stress_TH, levels = c("Augmentation de la douleur", "Pas d'impact sur la douleur", "Diminution de la douleur"), ordered = TRUE)

Evolution_Stress_TH <- ifelse(data$Evolution_Stress_TH == "", "0", data$Evolution_Stress_TH)
data$Evolution_Stress_TH <- factor(Evolution_Stress_TH, levels = c("Apparition de nouvelles lésions", "Grossissement des lésions déjà présentes", "Pas d'évolution", "Réduction modérée des lésions", "Réduction importante voire disparition des lésions", "Ne sais pas"), ordered = TRUE)


# Phyto TH #
Combien_Phyto_TH <- ifelse(data$Combien_Phyto_TH == "", "0", data$Combien_Phyto_TH)
data$Combien_Phyto_TH <- factor(Combien_Phyto_TH, levels = c("Moins de 3 mois", "Entre 3 et 6 mois", "Entre 6 mois et 2 ans", "Entre 2 et 5 ans", "Plus de 5 ans"), ordered = TRUE)

Douleur_Phyto_TH <- ifelse(data$Douleur_Phyto_TH == "", "0", data$Douleur_Phyto_TH)
data$Douleur_Phyto_TH <- factor(Douleur_Phyto_TH, levels = c("Augmentation de la douleur", "Pas d'impact sur la douleur", "Diminution de la douleur"), ordered = TRUE)

Evolution_Phyto_TH <- ifelse(data$Evolution_Phyto_TH == "", "0", data$Evolution_Phyto_TH)
data$Evolution_Phyto_TH <- factor(Evolution_Phyto_TH, levels = c("Apparition de nouvelles lésions", "Grossissement des lésions déjà présentes", "Pas d'évolution", "Réduction modérée des lésions", "Réduction importante voire disparition des lésions", "Ne sais pas"), ordered = TRUE)


# Acup TH #
Combien_Acup_TH <- ifelse(data$Combien_Acup_TH == "", "0", data$Combien_Acup_TH)
data$Combien_Acup_TH <- factor(Combien_Acup_TH, levels = c("Moins de 3 mois", "Entre 3 et 6 mois", "Entre 6 mois et 2 ans", "Entre 2 et 5 ans", "Plus de 5 ans"), ordered = TRUE)

Douleur_Acup_TH <- ifelse(data$Douleur_Acup_TH == "", "0", data$Douleur_Acup_TH)
data$Douleur_Acup_TH <- factor(Douleur_Acup_TH, levels = c("Augmentation de la douleur", "Pas d'impact sur la douleur", "Diminution de la douleur"), ordered = TRUE)

Evolution_Acup_TH <- ifelse(data$Evolution_Acup_TH == "", "0", data$Evolution_Acup_TH)
data$Evolution_Acup_TH <- factor(Evolution_Acup_TH, levels = c("Apparition de nouvelles lésions", "Grossissement des lésions déjà présentes", "Pas d'évolution", "Réduction modérée des lésions", "Réduction importante voire disparition des lésions", "Ne sais pas"), ordered = TRUE)



# Hypnose TH #
Combien_Hypnose_TH <- ifelse(data$Combien_Hypnose_TH == "", "0", data$Combien_Hypnose_TH)
data$Combien_Hypnose_TH <- factor(Combien_Hypnose_TH, levels = c("Moins de 3 mois", "Entre 3 et 6 mois", "Entre 6 mois et 2 ans", "Entre 2 et 5 ans", "Plus de 5 ans"), ordered = TRUE)

Douleur_Hypnose_TH <- ifelse(data$Douleur_Hypnose_TH == "", "0", data$Douleur_Hypnose_TH)
data$Douleur_Hypnose_TH <- factor(Douleur_Hypnose_TH, levels = c("Augmentation de la douleur", "Pas d'impact sur la douleur", "Diminution de la douleur"), ordered = TRUE)

Evolution_Hypnose_TH <- ifelse(data$Evolution_Hypnose_TH == "", "0", data$Evolution_Hypnose_TH)
data$Evolution_Hypnose_TH <- factor(Evolution_Hypnose_TH, levels = c("Apparition de nouvelles lésions", "Grossissement des lésions déjà présentes", "Pas d'évolution", "Réduction modérée des lésions", "Réduction importante voire disparition des lésions", "Ne sais pas"), ordered = TRUE)


# Bouillotte TH #
Combien_Bouillotte_TH <- ifelse(data$Combien_Bouillotte_TH == "", "0", data$Combien_Bouillotte_TH)
data$Combien_Bouillotte_TH <- factor(Combien_Bouillotte_TH, levels = c("Moins de 3 mois", "Entre 3 et 6 mois", "Entre 6 mois et 2 ans", "Entre 2 et 5 ans", "Plus de 5 ans"), ordered = TRUE)

Douleur_Bouillotte_TH <- ifelse(data$Douleur_Bouillotte_TH == "", "0", data$Douleur_Bouillotte_TH)
data$Douleur_Bouillotte_TH <- factor(Douleur_Bouillotte_TH, levels = c("Augmentation de la douleur", "Pas d'impact sur la douleur", "Diminution de la douleur"), ordered = TRUE)

Evolution_Bouillotte_TH <- ifelse(data$Evolution_Bouillotte_TH == "", "0", data$Evolution_Bouillotte_TH)
data$Evolution_Bouillotte_TH <- factor(Evolution_Bouillotte_TH, levels = c("Apparition de nouvelles lésions", "Grossissement des lésions déjà présentes", "Pas d'évolution", "Réduction modérée des lésions", "Réduction importante voire disparition des lésions", "Ne sais pas"), ordered = TRUE)


# CBD TH #
Combien_CBD_TH <- ifelse(data$Combien_CBD_TH == "", "0", data$Combien_CBD_TH)
data$Combien_CBD_TH <- factor(Combien_CBD_TH, levels = c("Moins de 3 mois", "Entre 3 et 6 mois", "Entre 6 mois et 2 ans", "Entre 2 et 5 ans", "Plus de 5 ans"), ordered = TRUE)

Douleur_CBD_TH <- ifelse(data$Douleur_CBD_TH == "", "0", data$Douleur_CBD_TH)
data$Douleur_CBD_TH <- factor(Douleur_CBD_TH, levels = c("Augmentation de la douleur", "Pas d'impact sur la douleur", "Diminution de la douleur"), ordered = TRUE)

Evolution_CBD_TH <- ifelse(data$Evolution_CBD_TH == "", "0", data$Evolution_CBD_TH)
data$Evolution_CBD_TH <- factor(Evolution_CBD_TH, levels = c("Apparition de nouvelles lésions", "Grossissement des lésions déjà présentes", "Pas d'évolution", "Réduction modérée des lésions", "Réduction importante voire disparition des lésions", "Ne sais pas"), ordered = TRUE)


# Tens TH #
Combien_Tens_TH <- ifelse(data$Combien_Tens_TH == "", "0", data$Combien_Tens_TH)
data$Combien_Tens_TH <- factor(Combien_Tens_TH, levels = c("Moins de 3 mois", "Entre 3 et 6 mois", "Entre 6 mois et 2 ans", "Entre 2 et 5 ans", "Plus de 5 ans"), ordered = TRUE)

Douleur_Tens_TH <- ifelse(data$Douleur_Tens_TH == "", "0", data$Douleur_Tens_TH)
data$Douleur_Tens_TH <- factor(Douleur_Tens_TH, levels = c("Augmentation de la douleur", "Pas d'impact sur la douleur", "Diminution de la douleur"), ordered = TRUE)

Evolution_Tens_TH <- ifelse(data$Evolution_Tens_TH == "", "0", data$Evolution_Tens_TH)
data$Evolution_Tens_TH <- factor(Evolution_Tens_TH, levels = c("Apparition de nouvelles lésions", "Grossissement des lésions déjà présentes", "Pas d'évolution", "Réduction modérée des lésions", "Réduction importante voire disparition des lésions", "Ne sais pas"), ordered = TRUE)

Depuis_CM <- ifelse(data$Depuis_CM == "", "0", data$Depuis_CM)
data$Depuis_CM <- factor(Depuis_CM, levels = c("Moins de 3 mois", "Entre 3 et 6 mois", "Entre 6 mois et 2 ans", "Entre 2 et 5 ans", "Plus de 5 ans"), ordered = TRUE)

Combien_CM <- ifelse(data$Combien_CM == "", "0", data$Combien_CM)
data$Combien_CM <- factor(Combien_CM, levels = c("Moins de 3 mois", "Entre 3 et 6 mois", "Entre 6 mois et 2 ans", "Entre 2 et 5 ans", "Plus de 5 ans"), ordered = TRUE)

Duree_CM <- factor(ifelse(is.na(data$Depuis_CM), as.character(data$Combien_CM), as.character(data$Depuis_CM)))

Douleur_CM <- ifelse(data$Douleur_CM == "", "0", data$Douleur_CM)
data$Douleur_CM <- factor(Douleur_CM, levels = c("Augmentation de la douleur", "Pas d'impact sur la douleur", "Réduction légère de la douleur", "Réduction importante de la douleur"), ordered = TRUE)

Evolution_CM <- ifelse(data$Evolution_CM == "", "0", data$Evolution_CM)
data$Evolution_CM <- factor(Evolution_CM, levels = c("Apparition de nouvelles lésions", "Grossissement des lésions déjà présentes", "Pas d'évolution", "Réduction modérée des lésions", "Réduction importante voire disparition des lésions", "Ne sais pas"), ordered = TRUE)

### Effets secondaires CM ###
Subi_ES_CM <- ifelse(data$Subi_ES_CM == "", "0", data$Subi_ES_CM)
data$Subi_ES_CM <- factor(Subi_ES_CM, levels = c("yes", "no"), ordered = TRUE)

Tete_CM <- ifelse(data$Tete_CM == "X", "y", "n")
data$Tete_CM <- factor(Tete_CM, levels = c("y", "n"), labels = c("yes", "no"))

Fatigue_CM <- ifelse(data$Fatigue_CM == "X", "y", "n")
data$Fatigue_CM <- factor(Fatigue_CM, levels = c("y", "n"), labels = c("yes", "no"))

Nausee_CM <- ifelse(data$Nausee_CM == "X", "y", "n")
data$Nausee_CM <- factor(Nausee_CM, levels = c("y", "n"), labels = c("yes", "no"))

Humeur_CM <- ifelse(data$Humeur_CM == "X", "y", "n")
data$Humeur_CM <- factor(Humeur_CM, levels = c("y", "n"), labels = c("yes", "no"))

Libido_CM <- ifelse(data$Libido_CM == "X", "y", "n")
data$Libido_CM <- factor(Libido_CM, levels = c("y", "n"), labels = c("yes", "no"))

Sang_CM <- ifelse(data$Sang_CM == "X", "y", "n")
data$Sang_CM <- factor(Sang_CM, levels = c("y", "n"), labels = c("yes", "no"))

Poids_CM <- ifelse(data$Poids_CM == "X", "y", "n")
data$Poids_CM <- factor(Poids_CM, levels = c("y", "n"), labels = c("yes", "no"))

Allergie_CM <- ifelse(data$Allergie_CM == "X", "y", "n")
data$Allergie_CM <- factor(Allergie_CM, levels = c("y", "n"), labels = c("yes", "no"))

Thrombose_CM <- ifelse(data$Thrombose_CM == "X", "y", "n")
data$Thrombose_CM <- factor(Thrombose_CM, levels = c("y", "n"), labels = c("yes", "no"))

Apparition_Tete_CM <- ifelse(data$Apparition_Tete_CM == "", "0", data$Apparition_Tete_CM)
data$Apparition_Tete_CM <- factor(Apparition_Tete_CM, levels = c("Moins de 3 mois", "Entre 3 et 6 mois", "Entre 6 mois et 2 ans", "Entre 2 et 5 ans", "Plus de 5 ans"), ordered = TRUE)

Frequence_Tete_CM <- ifelse(data$Frequence_Tete_CM == "", "0", data$Frequence_Tete_CM)
data$Frequence_Tete_CM <- factor(Frequence_Tete_CM, levels = c("Plusieurs fois par jour", "Plusieurs fois par semaine", "Plusieurs fois par mois", "Plusieurs fois par an", "Moins d'une fois par an"), ordered = TRUE)

Apparition_Fatigue_CM <- ifelse(data$Apparition_Fatigue_CM == "", "0", data$Apparition_Fatigue_CM)
data$Apparition_Fatigue_CM <- factor(Apparition_Fatigue_CM, levels = c("Moins de 3 mois", "Entre 3 et 6 mois", "Entre 6 mois et 2 ans", "Entre 2 et 5 ans", "Plus de 5 ans"), ordered = TRUE)

Frequence_Fatigue_CM <- ifelse(data$Frequence_Fatigue_CM == "", "0", data$Frequence_Fatigue_CM)
data$Frequence_Fatigue_CM <- factor(Frequence_Fatigue_CM, levels = c("Plusieurs fois par jour", "Plusieurs fois par semaine", "Plusieurs fois par mois", "Plusieurs fois par an", "Moins d'une fois par an"), ordered = TRUE)

Apparition_Nausee_CM <- ifelse(data$Apparition_Nausee_CM == "", "0", data$Apparition_Nausee_CM)
data$Apparition_Nausee_CM <- factor(Apparition_Nausee_CM, levels = c("Moins de 3 mois", "Entre 3 et 6 mois", "Entre 6 mois et 2 ans", "Entre 2 et 5 ans", "Plus de 5 ans"), ordered = TRUE)

Frequence_Nausee_CM <- ifelse(data$Frequence_Nausee_CM == "", "0", data$Frequence_Nausee_CM)
data$Frequence_Nausee_CM <- factor(Frequence_Nausee_CM, levels = c("Plusieurs fois par jour", "Plusieurs fois par semaine", "Plusieurs fois par mois", "Plusieurs fois par an", "Moins d'une fois par an"), ordered = TRUE)

Apparition_Humeur_CM <- ifelse(data$Apparition_Humeur_CM == "", "0", data$Apparition_Humeur_CM)
data$Apparition_Humeur_CM <- factor(Apparition_Humeur_CM, levels = c("Moins de 3 mois", "Entre 3 et 6 mois", "Entre 6 mois et 2 ans", "Entre 2 et 5 ans", "Plus de 5 ans"), ordered = TRUE)

Frequence_Humeur_CM <- ifelse(data$Frequence_Humeur_CM == "", "0", data$Frequence_Humeur_CM)
data$Frequence_Humeur_CM <- factor(Frequence_Humeur_CM, levels = c("Plusieurs fois par jour", "Plusieurs fois par semaine", "Plusieurs fois par mois", "Plusieurs fois par an", "Moins d'une fois par an"), ordered = TRUE)

Apparition_Libido_CM <- ifelse(data$Apparition_Libido_CM == "", "0", data$Apparition_Libido_CM)
data$Apparition_Libido_CM <- factor(Apparition_Libido_CM, levels = c("Moins de 3 mois", "Entre 3 et 6 mois", "Entre 6 mois et 2 ans", "Entre 2 et 5 ans", "Plus de 5 ans"), ordered = TRUE)

Frequence_Libido_CM <- ifelse(data$Frequence_Libido_CM == "", "0", data$Frequence_Libido_CM)
data$Frequence_Libido_CM <- factor(Frequence_Libido_CM, levels = c("Plusieurs fois par jour", "Plusieurs fois par semaine", "Plusieurs fois par mois", "Plusieurs fois par an", "Moins d'une fois par an"), ordered = TRUE)

Apparition_Sang_CM <- ifelse(data$Apparition_Sang_CM == "", "0", data$Apparition_Sang_CM)
data$Apparition_Sang_CM <- factor(Apparition_Sang_CM, levels = c("Moins de 3 mois", "Entre 3 et 6 mois", "Entre 6 mois et 2 ans", "Entre 2 et 5 ans", "Plus de 5 ans"), ordered = TRUE)

Frequence_Sang_CM <- ifelse(data$Frequence_Sang_CM == "", "0", data$Frequence_Sang_CM)
data$Frequence_Sang_CM <- factor(Frequence_Sang_CM, levels = c("Plusieurs fois par jour", "Plusieurs fois par semaine", "Plusieurs fois par mois", "Plusieurs fois par an", "Moins d'une fois par an"), ordered = TRUE)

Apparition_Thrombose_CM <- ifelse(data$Apparition_Thrombose_CM == "", "0", data$Apparition_Thrombose_CM)
data$Apparition_Thrombose_CM <- factor(Apparition_Thrombose_CM, levels = c("Moins de 3 mois", "Entre 3 et 6 mois", "Entre 6 mois et 2 ans", "Entre 2 et 5 ans", "Plus de 5 ans"), ordered = TRUE)

### Traitements non médicamenteux CM ###
Mobilite_CM <- ifelse(data$Mobilite_CM == "X", "y", "n")
data$Mobilite_CM <- factor(Mobilite_CM, levels = c("y", "n"), labels = c("yes", "no"))

Nutrition_CM <- ifelse(data$Nutrition_CM == "X", "y", "n")
data$Nutrition_CM <- factor(Nutrition_CM, levels = c("y", "n"), labels = c("yes", "no"))

Stress_CM <- ifelse(data$Stress_CM == "X", "y", "n")
data$Stress_CM <- factor(Stress_CM, levels = c("y", "n"), labels = c("yes", "no"))

Phyto_CM <- ifelse(data$Phyto_CM == "X", "y", "n")
data$Phyto_CM <- factor(Phyto_CM, levels = c("y", "n"), labels = c("yes", "no"))

Acup_CM <- ifelse(data$Acup_CM == "X", "y", "n")
data$Acup_CM <- factor(Acup_CM, levels = c("y", "n"), labels = c("yes", "no"))

Hypnose_CM <- ifelse(data$Hypnose_CM == "X", "y", "n")
data$Hypnose_CM <- factor(Hypnose_CM, levels = c("y", "n"), labels = c("yes", "no"))

Bouillotte_CM <- ifelse(data$Bouillotte_CM == "X", "y", "n")
data$Bouillotte_CM <- factor(Bouillotte_CM, levels = c("y", "n"), labels = c("yes", "no"))

CBD_CM <- ifelse(data$CBD_CM == "X", "y", "n")
data$CBD_CM <- factor(CBD_CM, levels = c("y", "n"), labels = c("yes", "no"))

Tens_CM <- ifelse(data$Tens_CM == "X", "y", "n")
data$Tens_CM <- factor(Tens_CM, levels = c("y", "n"), labels = c("yes", "no"))

Aucun_CM <- ifelse(data$Aucun_CM == "X", "y", "n")
data$Aucun_CM <- factor(Aucun_CM, levels = c("y", "n"), labels = c("yes", "no"))

# Mobilité CM #
Combien_Mobilite_CM <- ifelse(data$Combien_Mobilite_CM == "", "0", data$Combien_Mobilite_CM)
data$Combien_Mobilite_CM <- factor(Combien_Mobilite_CM, levels = c("Moins de 3 mois", "Entre 3 et 6 mois", "Entre 6 mois et 2 ans", "Entre 2 et 5 ans", "Plus de 5 ans"), ordered = TRUE)

Douleur_Mobilite_CM <- ifelse(data$Douleur_Mobilite_CM == "", "0", data$Douleur_Mobilite_CM)
data$Douleur_Mobilite_CM <- factor(Douleur_Mobilite_CM, levels = c("Augmentation de la douleur", "Pas d'impact sur la douleur", "Diminution de la douleur"), ordered = TRUE)

Evolution_Mobilite_CM <- ifelse(data$Evolution_Mobilite_CM == "", "0", data$Evolution_Mobilite_CM)
data$Evolution_Mobilite_CM <- factor(Evolution_Mobilite_CM, levels = c("Apparition de nouvelles lésions", "Grossissement des lésions déjà présentes", "Pas d'évolution", "Réduction modérée des lésions", "Réduction importante voire disparition des lésions", "Ne sais pas"), ordered = TRUE)


# Nutrition CM #
Combien_Nutrition_CM <- ifelse(data$Combien_Nutrition_CM == "", "0", data$Combien_Nutrition_CM)
data$Combien_Nutrition_CM <- factor(Combien_Nutrition_CM, levels = c("Moins de 3 mois", "Entre 3 et 6 mois", "Entre 6 mois et 2 ans", "Entre 2 et 5 ans", "Plus de 5 ans"), ordered = TRUE)

Douleur_Nutrition_CM <- ifelse(data$Douleur_Nutrition_CM == "", "0", data$Douleur_Nutrition_CM)
data$Douleur_Nutrition_CM <- factor(Douleur_Nutrition_CM, levels = c("Augmentation de la douleur", "Pas d'impact sur la douleur", "Diminution de la douleur"), ordered = TRUE)

Evolution_Nutrition_CM <- ifelse(data$Evolution_Nutrition_CM == "", "0", data$Evolution_Nutrition_CM)
data$Evolution_Nutrition_CM <- factor(Evolution_Nutrition_CM, levels = c("Apparition de nouvelles lésions", "Grossissement des lésions déjà présentes", "Pas d'évolution", "Réduction modérée des lésions", "Réduction importante voire disparition des lésions", "Ne sais pas"), ordered = TRUE)


# Stress CM #
Combien_Stress_CM <- ifelse(data$Combien_Stress_CM == "", "0", data$Combien_Stress_CM)
data$Combien_Stress_CM <- factor(Combien_Stress_CM, levels = c("Moins de 3 mois", "Entre 3 et 6 mois", "Entre 6 mois et 2 ans", "Entre 2 et 5 ans", "Plus de 5 ans"), ordered = TRUE)

Douleur_Stress_CM <- ifelse(data$Douleur_Stress_CM == "", "0", data$Douleur_Stress_CM)
data$Douleur_Stress_CM <- factor(Douleur_Stress_CM, levels = c("Augmentation de la douleur", "Pas d'impact sur la douleur", "Diminution de la douleur"), ordered = TRUE)

Evolution_Stress_CM <- ifelse(data$Evolution_Stress_CM == "", "0", data$Evolution_Stress_CM)
data$Evolution_Stress_CM <- factor(Evolution_Stress_CM, levels = c("Apparition de nouvelles lésions", "Grossissement des lésions déjà présentes", "Pas d'évolution", "Réduction modérée des lésions", "Réduction importante voire disparition des lésions", "Ne sais pas"), ordered = TRUE)


# Phyto CM #
Combien_Phyto_CM <- ifelse(data$Combien_Phyto_CM == "", "0", data$Combien_Phyto_CM)
data$Combien_Phyto_CM <- factor(Combien_Phyto_CM, levels = c("Moins de 3 mois", "Entre 3 et 6 mois", "Entre 6 mois et 2 ans", "Entre 2 et 5 ans", "Plus de 5 ans"), ordered = TRUE)

Douleur_Phyto_CM <- ifelse(data$Douleur_Phyto_CM == "", "0", data$Douleur_Phyto_CM)
data$Douleur_Phyto_CM <- factor(Douleur_Phyto_CM, levels = c("Augmentation de la douleur", "Pas d'impact sur la douleur", "Diminution de la douleur"), ordered = TRUE)

Evolution_Phyto_CM <- ifelse(data$Evolution_Phyto_CM == "", "0", data$Evolution_Phyto_CM)
data$Evolution_Phyto_CM <- factor(Evolution_Phyto_CM, levels = c("Apparition de nouvelles lésions", "Grossissement des lésions déjà présentes", "Pas d'évolution", "Réduction modérée des lésions", "Réduction importante voire disparition des lésions", "Ne sais pas"), ordered = TRUE)


# Acup CM #
Combien_Acup_CM <- ifelse(data$Combien_Acup_CM == "", "0", data$Combien_Acup_CM)
data$Combien_Acup_CM <- factor(Combien_Acup_CM, levels = c("Moins de 3 mois", "Entre 3 et 6 mois", "Entre 6 mois et 2 ans", "Entre 2 et 5 ans", "Plus de 5 ans"), ordered = TRUE)

Douleur_Acup_CM <- ifelse(data$Douleur_Acup_CM == "", "0", data$Douleur_Acup_CM)
data$Douleur_Acup_CM <- factor(Douleur_Acup_CM, levels = c("Augmentation de la douleur", "Pas d'impact sur la douleur", "Diminution de la douleur"), ordered = TRUE)

Evolution_Acup_CM <- ifelse(data$Evolution_Acup_CM == "", "0", data$Evolution_Acup_CM)
data$Evolution_Acup_CM <- factor(Evolution_Acup_CM, levels = c("Apparition de nouvelles lésions", "Grossissement des lésions déjà présentes", "Pas d'évolution", "Réduction modérée des lésions", "Réduction importante voire disparition des lésions", "Ne sais pas"), ordered = TRUE)


# Hypnose CM #
Combien_Hypnose_CM <- ifelse(data$Combien_Hypnose_CM == "", "0", data$Combien_Hypnose_CM)
data$Combien_Hypnose_CM <- factor(Combien_Hypnose_CM, levels = c("Moins de 3 mois", "Entre 3 et 6 mois", "Entre 6 mois et 2 ans", "Entre 2 et 5 ans", "Plus de 5 ans"), ordered = TRUE)

Douleur_Hypnose_CM <- ifelse(data$Douleur_Hypnose_CM == "", "0", data$Douleur_Hypnose_CM)
data$Douleur_Hypnose_CM <- factor(Douleur_Hypnose_CM, levels = c("Augmentation de la douleur", "Pas d'impact sur la douleur", "Diminution de la douleur"), ordered = TRUE)

Evolution_Hypnose_CM <- ifelse(data$Evolution_Hypnose_CM == "", "0", data$Evolution_Hypnose_CM)
data$Evolution_Hypnose_CM <- factor(Evolution_Hypnose_CM, levels = c("Apparition de nouvelles lésions", "Grossissement des lésions déjà présentes", "Pas d'évolution", "Réduction modérée des lésions", "Réduction importante voire disparition des lésions", "Ne sais pas"), ordered = TRUE)


# Bouillotte CM #
Combien_Bouillotte_CM <- ifelse(data$Combien_Bouillotte_CM == "", "0", data$Combien_Bouillotte_CM)
data$Combien_Bouillotte_CM <- factor(Combien_Bouillotte_CM, levels = c("Moins de 3 mois", "Entre 3 et 6 mois", "Entre 6 mois et 2 ans", "Entre 2 et 5 ans", "Plus de 5 ans"), ordered = TRUE)

Douleur_Bouillotte_CM <- ifelse(data$Douleur_Bouillotte_CM == "", "0", data$Douleur_Bouillotte_CM)
data$Douleur_Bouillotte_CM <- factor(Douleur_Bouillotte_CM, levels = c("Augmentation de la douleur", "Pas d'impact sur la douleur", "Diminution de la douleur"), ordered = TRUE)

Evolution_Bouillotte_CM <- ifelse(data$Evolution_Bouillotte_CM == "", "0", data$Evolution_Bouillotte_CM)
data$Evolution_Bouillotte_CM <- factor(Evolution_Bouillotte_CM, levels = c("Apparition de nouvelles lésions", "Grossissement des lésions déjà présentes", "Pas d'évolution", "Réduction modérée des lésions", "Réduction importante voire disparition des lésions", "Ne sais pas"), ordered = TRUE)


# CBD CM #
Combien_CBD_CM <- ifelse(data$Combien_CBD_CM == "", "0", data$Combien_CBD_CM)
data$Combien_CBD_CM <- factor(Combien_CBD_CM, levels = c("Moins de 3 mois", "Entre 3 et 6 mois", "Entre 6 mois et 2 ans", "Entre 2 et 5 ans", "Plus de 5 ans"), ordered = TRUE)

Douleur_CBD_CM <- ifelse(data$Douleur_CBD_CM == "", "0", data$Douleur_CBD_CM)
data$Douleur_CBD_CM <- factor(Douleur_CBD_CM, levels = c("Augmentation de la douleur", "Pas d'impact sur la douleur", "Diminution de la douleur"), ordered = TRUE)

Evolution_CBD_CM <- ifelse(data$Evolution_CBD_CM == "", "0", data$Evolution_CBD_CM)
data$Evolution_CBD_CM <- factor(Evolution_CBD_CM, levels = c("Apparition de nouvelles lésions", "Grossissement des lésions déjà présentes", "Pas d'évolution", "Réduction modérée des lésions", "Réduction importante voire disparition des lésions", "Ne sais pas"), ordered = TRUE)


# Tens CM #
Combien_Tens_CM <- ifelse(data$Combien_Tens_CM == "", "0", data$Combien_Tens_CM)
data$Combien_Tens_CM <- factor(Combien_Tens_CM, levels = c("Moins de 3 mois", "Entre 3 et 6 mois", "Entre 6 mois et 2 ans", "Entre 2 et 5 ans", "Plus de 5 ans"), ordered = TRUE)

Douleur_Tens_CM <- ifelse(data$Douleur_Tens_CM == "", "0", data$Douleur_Tens_CM)
data$Douleur_Tens_CM <- factor(Douleur_Tens_CM, levels = c("Augmentation de la douleur", "Pas d'impact sur la douleur", "Diminution de la douleur"), ordered = TRUE)

Evolution_Tens_CM <- ifelse(data$Evolution_Tens_CM == "", "0", data$Evolution_Tens_CM)
data$Evolution_Tens_CM <- factor(Evolution_Tens_CM, levels = c("Apparition de nouvelles lésions", "Grossissement des lésions déjà présentes", "Pas d'évolution", "Réduction modérée des lésions", "Réduction importante voire disparition des lésions", "Ne sais pas"), ordered = TRUE)

### Traitements non médicamenteux seuls ###
Mobilite_NM <- ifelse(data$Mobilite_NM == "X", "y", "n")
data$Mobilite_NM <- factor(Mobilite_NM, levels = c("y", "n"), labels = c("yes", "no"))

Nutrition_NM <- ifelse(data$Nutrition_NM == "X", "y", "n")
data$Nutrition_NM <- factor(Nutrition_NM, levels = c("y", "n"), labels = c("yes", "no"))

Stress_NM <- ifelse(data$Stress_NM == "X", "y", "n")
data$Stress_NM <- factor(Stress_NM, levels = c("y", "n"), labels = c("yes", "no"))

Phyto_NM <- ifelse(data$Phyto_NM == "X", "y", "n")
data$Phyto_NM <- factor(Phyto_NM, levels = c("y", "n"), labels = c("yes", "no"))

Acup_NM <- ifelse(data$Acup_NM == "X", "y", "n")
data$Acup_NM <- factor(Acup_NM, levels = c("y", "n"), labels = c("yes", "no"))

Hypnose_NM <- ifelse(data$Hypnose_NM == "X", "y", "n")
data$Hypnose_NM <- factor(Hypnose_NM, levels = c("y", "n"), labels = c("yes", "no"))

Bouillotte_NM <- ifelse(data$Bouillotte_NM == "X", "y", "n")
data$Bouillotte_NM <- factor(Bouillotte_NM, levels = c("y", "n"), labels = c("yes", "no"))

CBD_NM <- ifelse(data$CBD_NM == "X", "y", "n")
data$CBD_NM <- factor(CBD_NM, levels = c("y", "n"), labels = c("yes", "no"))

Tens_NM <- ifelse(data$Tens_NM == "X", "y", "n")
data$Tens_NM <- factor(Tens_NM, levels = c("y", "n"), labels = c("yes", "no"))

Aucun_NM <- ifelse(data$Aucun_NM == "X", "y", "n")
data$Aucun_NM <- factor(Aucun_NM, levels = c("y", "n"), labels = c("yes", "no"))


# Mobilité NM #

Depuis_Mobilite_NM <- ifelse(data$Depuis_Mobilite_NM == "", "0", data$Depuis_Mobilite_NM)
data$Depuis_Mobilite_NM <- factor(Depuis_Mobilite_NM, levels = c("Moins de 3 mois", "Entre 3 et 6 mois", "Entre 6 mois et 2 ans", "Entre 2 et 5 ans", "Plus de 5 ans"), ordered = TRUE)

Combien_Mobilite_NM <- ifelse(data$Combien_Mobilite_NM == "", "0", data$Combien_Mobilite_NM)
data$Combien_Mobilite_NM <- factor(Combien_Mobilite_NM, levels = c("Moins de 3 mois", "Entre 3 et 6 mois", "Entre 6 mois et 2 ans", "Entre 2 et 5 ans", "Plus de 5 ans"), ordered = TRUE)

Duree_M <- factor(ifelse(is.na(data$Depuis_Mobilite_NM), as.character(data$Combien_Mobilite_NM), as.character(data$Depuis_Mobilite_NM)))

Douleur_Mobilite_NM <- ifelse(data$Douleur_Mobilite_NM == "", "0", data$Douleur_Mobilite_NM)
data$Douleur_Mobilite_NM <- factor(Douleur_Mobilite_NM, levels = c("Augmentation de la douleur", "Pas d'impact sur la douleur", "Réduction légère de la douleur", "Réduction importante de la douleur"), ordered = TRUE)

Evolution_Mobilite_NM <- ifelse(data$Evolution_Mobilite_NM == "", "0", data$Evolution_Mobilite_NM)
data$Evolution_Mobilite_NM <- factor(Evolution_Mobilite_NM, levels = c("Apparition de nouvelles lésions", "Grossissement des lésions déjà présentes", "Pas d'évolution", "Réduction modérée des lésions", "Réduction importante voire disparition des lésions", "Ne sais pas"), ordered = TRUE)

# Nutrition NM #

Depuis_Nutrition_NM <- ifelse(data$Depuis_Nutrition_NM == "", "0", data$Depuis_Nutrition_NM)
data$Depuis_Nutrition_NM <- factor(Depuis_Nutrition_NM, levels = c("Moins de 3 mois", "Entre 3 et 6 mois", "Entre 6 mois et 2 ans", "Entre 2 et 5 ans", "Plus de 5 ans"), ordered = TRUE)

Combien_Nutrition_NM <- ifelse(data$Combien_Nutrition_NM == "", "0", data$Combien_Nutrition_NM)
data$Combien_Nutrition_NM <- factor(Combien_Nutrition_NM, levels = c("Moins de 3 mois", "Entre 3 et 6 mois", "Entre 6 mois et 2 ans", "Entre 2 et 5 ans", "Plus de 5 ans"), ordered = TRUE)

Duree_N <- factor(ifelse(is.na(data$Depuis_Nutrition_NM), as.character(data$Combien_Nutrition_NM), as.character(data$Depuis_Nutrition_NM)))

Douleur_Nutrition_NM <- ifelse(data$Douleur_Nutrition_NM == "", "0", data$Douleur_Nutrition_NM)
data$Douleur_Nutrition_NM <- factor(Douleur_Nutrition_NM, levels = c("Augmentation de la douleur", "Pas d'impact sur la douleur", "Réduction légère de la douleur", "Réduction importante de la douleur"), ordered = TRUE)

Evolution_Nutrition_NM <- ifelse(data$Evolution_Nutrition_NM == "", "0", data$Evolution_Nutrition_NM)
data$Evolution_Nutrition_NM <- factor(Evolution_Nutrition_NM, levels = c("Apparition de nouvelles lésions", "Grossissement des lésions déjà présentes", "Pas d'évolution", "Réduction modérée des lésions", "Réduction importante voire disparition des lésions", "Ne sais pas"), ordered = TRUE)


# Stress NM #

Depuis_Stress_NM <- ifelse(data$Depuis_Stress_NM == "", "0", data$Depuis_Stress_NM)
data$Depuis_Stress_NM <- factor(Depuis_Stress_NM, levels = c("Moins de 3 mois", "Entre 3 et 6 mois", "Entre 6 mois et 2 ans", "Entre 2 et 5 ans", "Plus de 5 ans"), ordered = TRUE)

Combien_Stress_NM <- ifelse(data$Combien_Stress_NM == "", "0", data$Combien_Stress_NM)
data$Combien_Stress_NM <- factor(Combien_Stress_NM, levels = c("Moins de 3 mois", "Entre 3 et 6 mois", "Entre 6 mois et 2 ans", "Entre 2 et 5 ans", "Plus de 5 ans"), ordered = TRUE)

Duree_S <- factor(ifelse(is.na(data$Depuis_Stress_NM), as.character(data$Combien_Stress_NM), as.character(data$Depuis_Stress_NM)))

Douleur_Stress_NM <- ifelse(data$Douleur_Stress_NM == "", "0", data$Douleur_Stress_NM)
data$Douleur_Stress_NM <- factor(Douleur_Stress_NM, levels = c("Augmentation de la douleur", "Pas d'impact sur la douleur", "Réduction légère de la douleur", "Réduction importante de la douleur"), ordered = TRUE)

Evolution_Stress_NM <- ifelse(data$Evolution_Stress_NM == "", "0", data$Evolution_Stress_NM)
data$Evolution_Stress_NM <- factor(Evolution_Stress_NM, levels = c("Apparition de nouvelles lésions", "Grossissement des lésions déjà présentes", "Pas d'évolution", "Réduction modérée des lésions", "Réduction importante voire disparition des lésions", "Ne sais pas"), ordered = TRUE)


# Phyto NM #

Depuis_Phyto_NM <- ifelse(data$Depuis_Phyto_NM == "", "0", data$Depuis_Phyto_NM)
data$Depuis_Phyto_NM <- factor(Depuis_Phyto_NM, levels = c("Moins de 3 mois", "Entre 3 et 6 mois", "Entre 6 mois et 2 ans", "Entre 2 et 5 ans", "Plus de 5 ans"), ordered = TRUE)

Combien_Phyto_NM <- ifelse(data$Combien_Phyto_NM == "", "0", data$Combien_Phyto_NM)
data$Combien_Phyto_NM <- factor(Combien_Phyto_NM, levels = c("Moins de 3 mois", "Entre 3 et 6 mois", "Entre 6 mois et 2 ans", "Entre 2 et 5 ans", "Plus de 5 ans"), ordered = TRUE)

Duree_P <- factor(ifelse(is.na(data$Depuis_Phyto_NM), as.character(data$Combien_Phyto_NM), as.character(data$Depuis_Phyto_NM)))

Douleur_Phyto_NM <- ifelse(data$Douleur_Phyto_NM == "", "0", data$Douleur_Phyto_NM)
data$Douleur_Phyto_NM <- factor(Douleur_Phyto_NM, levels = c("Augmentation de la douleur", "Pas d'impact sur la douleur", "Réduction légère de la douleur", "Réduction importante de la douleur"), ordered = TRUE)

Evolution_Phyto_NM <- ifelse(data$Evolution_Phyto_NM == "", "0", data$Evolution_Phyto_NM)
data$Evolution_Phyto_NM <- factor(Evolution_Phyto_NM, levels = c("Apparition de nouvelles lésions", "Grossissement des lésions déjà présentes", "Pas d'évolution", "Réduction modérée des lésions", "Réduction importante voire disparition des lésions", "Ne sais pas"), ordered = TRUE)


# Acup NM #

Depuis_Acup_NM <- ifelse(data$Depuis_Acup_NM == "", "0", data$Depuis_Acup_NM)
data$Depuis_Acup_NM <- factor(Depuis_Acup_NM, levels = c("Moins de 3 mois", "Entre 3 et 6 mois", "Entre 6 mois et 2 ans", "Entre 2 et 5 ans", "Plus de 5 ans"), ordered = TRUE)

Combien_Acup_NM <- ifelse(data$Combien_Acup_NM == "", "0", data$Combien_Acup_NM)
data$Combien_Acup_NM <- factor(Combien_Acup_NM, levels = c("Moins de 3 mois", "Entre 3 et 6 mois", "Entre 6 mois et 2 ans", "Entre 2 et 5 ans", "Plus de 5 ans"), ordered = TRUE)

Duree_A <- factor(ifelse(is.na(data$Depuis_Acup_NM), as.character(data$Combien_Acup_NM), as.character(data$Depuis_Acup_NM)))

Douleur_Acup_NM <- ifelse(data$Douleur_Acup_NM == "", "0", data$Douleur_Acup_NM)
data$Douleur_Acup_NM <- factor(Douleur_Acup_NM, levels = c("Augmentation de la douleur", "Pas d'impact sur la douleur", "Réduction légère de la douleur", "Réduction importante de la douleur"), ordered = TRUE)

Evolution_Acup_NM <- ifelse(data$Evolution_Acup_NM == "", "0", data$Evolution_Acup_NM)
data$Evolution_Acup_NM <- factor(Evolution_Acup_NM, levels = c("Apparition de nouvelles lésions", "Grossissement des lésions déjà présentes", "Pas d'évolution", "Réduction modérée des lésions", "Réduction importante voire disparition des lésions", "Ne sais pas"), ordered = TRUE)


# Hypnose NM #

Depuis_Hypnose_NM <- ifelse(data$Depuis_Hypnose_NM == "", "0", data$Depuis_Hypnose_NM)
data$Depuis_Hypnose_NM <- factor(Depuis_Hypnose_NM, levels = c("Moins de 3 mois", "Entre 3 et 6 mois", "Entre 6 mois et 2 ans", "Entre 2 et 5 ans", "Plus de 5 ans"), ordered = TRUE)

Combien_Hypnose_NM <- ifelse(data$Combien_Hypnose_NM == "", "0", data$Combien_Hypnose_NM)
data$Combien_Hypnose_NM <- factor(Combien_Hypnose_NM, levels = c("Moins de 3 mois", "Entre 3 et 6 mois", "Entre 6 mois et 2 ans", "Entre 2 et 5 ans", "Plus de 5 ans"), ordered = TRUE)

Duree_H <- factor(ifelse(is.na(data$Depuis_Hypnose_NM), as.character(data$Combien_Hypnose_NM), as.character(data$Depuis_Hypnose_NM)))

Douleur_Hypnose_NM <- ifelse(data$Douleur_Hypnose_NM == "", "0", data$Douleur_Hypnose_NM)
data$Douleur_Hypnose_NM <- factor(Douleur_Hypnose_NM, levels = c("Augmentation de la douleur", "Pas d'impact sur la douleur", "Réduction légère de la douleur", "Réduction importante de la douleur"), ordered = TRUE)

Evolution_Hypnose_NM <- ifelse(data$Evolution_Hypnose_NM == "", "0", data$Evolution_Hypnose_NM)
data$Evolution_Hypnose_NM <- factor(Evolution_Hypnose_NM, levels = c("Apparition de nouvelles lésions", "Grossissement des lésions déjà présentes", "Pas d'évolution", "Réduction modérée des lésions", "Réduction importante voire disparition des lésions", "Ne sais pas"), ordered = TRUE)


# Bouillotte NM #

Depuis_Bouillotte_NM <- ifelse(data$Depuis_Bouillotte_NM == "", "0", data$Depuis_Bouillotte_NM)
data$Depuis_Bouillotte_NM <- factor(Depuis_Bouillotte_NM, levels = c("Moins de 3 mois", "Entre 3 et 6 mois", "Entre 6 mois et 2 ans", "Entre 2 et 5 ans", "Plus de 5 ans"), ordered = TRUE)

Combien_Bouillotte_NM <- ifelse(data$Combien_Bouillotte_NM == "", "0", data$Combien_Bouillotte_NM)
data$Combien_Bouillotte_NM <- factor(Combien_Bouillotte_NM, levels = c("Moins de 3 mois", "Entre 3 et 6 mois", "Entre 6 mois et 2 ans", "Entre 2 et 5 ans", "Plus de 5 ans"), ordered = TRUE)

Duree_B <- factor(ifelse(is.na(data$Depuis_Bouillotte_NM), as.character(data$Combien_Bouillotte_NM), as.character(data$Depuis_Bouillotte_NM)))

Douleur_Bouillotte_NM <- ifelse(data$Douleur_Bouillotte_NM == "", "0", data$Douleur_Bouillotte_NM)
data$Douleur_Bouillotte_NM <- factor(Douleur_Bouillotte_NM, levels = c("Augmentation de la douleur", "Pas d'impact sur la douleur", "Réduction légère de la douleur", "Réduction importante de la douleur"), ordered = TRUE)

Evolution_Bouillotte_NM <- ifelse(data$Evolution_Bouillotte_NM == "", "0", data$Evolution_Bouillotte_NM)
data$Evolution_Bouillotte_NM <- factor(Evolution_Bouillotte_NM, levels = c("Apparition de nouvelles lésions", "Grossissement des lésions déjà présentes", "Pas d'évolution", "Réduction modérée des lésions", "Réduction importante voire disparition des lésions", "Ne sais pas"), ordered = TRUE)


# CBD NM #

Depuis_CBD_NM <- ifelse(data$Depuis_CBD_NM == "", "0", data$Depuis_CBD_NM)
data$Depuis_CBD_NM <- factor(Depuis_CBD_NM, levels = c("Moins de 3 mois", "Entre 3 et 6 mois", "Entre 6 mois et 2 ans", "Entre 2 et 5 ans", "Plus de 5 ans"), ordered = TRUE)

Combien_CBD_NM <- ifelse(data$Combien_CBD_NM == "", "0", data$Combien_CBD_NM)
data$Combien_CBD_NM <- factor(Combien_CBD_NM, levels = c("Moins de 3 mois", "Entre 3 et 6 mois", "Entre 6 mois et 2 ans", "Entre 2 et 5 ans", "Plus de 5 ans"), ordered = TRUE)

Duree_C <- factor(ifelse(is.na(data$Depuis_CBD_NM), as.character(data$Combien_CBD_NM), as.character(data$Depuis_CBD_NM)))

Douleur_CBD_NM <- ifelse(data$Douleur_CBD_NM == "", "0", data$Douleur_CBD_NM)
data$Douleur_CBD_NM <- factor(Douleur_CBD_NM, levels = c("Augmentation de la douleur", "Pas d'impact sur la douleur", "Réduction légère de la douleur", "Réduction importante de la douleur"), ordered = TRUE)

Evolution_CBD_NM <- ifelse(data$Evolution_CBD_NM == "", "0", data$Evolution_CBD_NM)
data$Evolution_CBD_NM <- factor(Evolution_CBD_NM, levels = c("Apparition de nouvelles lésions", "Grossissement des lésions déjà présentes", "Pas d'évolution", "Réduction modérée des lésions", "Réduction importante voire disparition des lésions", "Ne sais pas"), ordered = TRUE)


# Tens NM #

Depuis_Tens_NM <- ifelse(data$Depuis_Tens_NM == "", "0", data$Depuis_Tens_NM)
data$Depuis_Tens_NM <- factor(Depuis_Tens_NM, levels = c("Moins de 3 mois", "Entre 3 et 6 mois", "Entre 6 mois et 2 ans", "Entre 2 et 5 ans", "Plus de 5 ans"), ordered = TRUE)

Combien_Tens_NM <- ifelse(data$Combien_Tens_NM == "", "0", data$Combien_Tens_NM)
data$Combien_Tens_NM <- factor(Combien_Tens_NM, levels = c("Moins de 3 mois", "Entre 3 et 6 mois", "Entre 6 mois et 2 ans", "Entre 2 et 5 ans", "Plus de 5 ans"), ordered = TRUE)

Duree_T <- factor(ifelse(is.na(data$Depuis_Tens_NM), as.character(data$Combien_Tens_NM), as.character(data$Depuis_Tens_NM)))

Douleur_Tens_NM <- ifelse(data$Douleur_Tens_NM == "", "0", data$Douleur_Tens_NM)
data$Douleur_Tens_NM <- factor(Douleur_Tens_NM, levels = c("Augmentation de la douleur", "Pas d'impact sur la douleur", "Réduction légère de la douleur", "Réduction importante de la douleur"), ordered = TRUE)

Evolution_Tens_NM <- ifelse(data$Evolution_Tens_NM == "", "0", data$Evolution_Tens_NM)
data$Evolution_Tens_NM <- factor(Evolution_Tens_NM, levels = c("Apparition de nouvelles lésions", "Grossissement des lésions déjà présentes", "Pas d'évolution", "Réduction modérée des lésions", "Réduction importante voire disparition des lésions", "Ne sais pas"), ordered = TRUE)
```




